### ISSUE TITLE
Concepticon mapping

### ISSUE THREAD

**Issue by laiyunfan** [lexibank/zhangrgyalrong#2]
So at first sight the automatic mapping is not very good, the coverage is low: 17/122 14% . Do we need manual mapping? @LinguList

**Comment by SimonGreenhill** [comment]
Ok, concepticon's been released now, right?

**Comment by LinguList** [comment]
Nope, this dataset is too specific in my opinion, to link it to
concepticon. Or do we link in general? If so, we'd need somebody to add
this to concepticon.

**Comment by LinguList** [comment]
Okay, @MacyL, @laiyunfan, I just checked the dataset. It looks like you can just add the concept list to concepticon, as you know it. Can I ask you to make a mapping proposal soon? Maybe @laiyunfan you could do the mapping and submit to Concepticon, and @MacyL you could manage the PR and the reviewers? Leave concepts in doubt just unmapped, this will be fine.

**Comment by MacyL** [comment]
I can help with that.

**Comment by laiyunfan** [comment]
Ok

**Comment by Tarotis** [comment]
@LinguList This is one of the last lists that is missing in concepticon. However, there are some issues on which you might be able to help:

- Two lists of Zhang exist in Concepticon: Zhang-2019-122, and a larger one with 308
- The larger list is linked in the metadata
- The shorter list is used in etc/
- The actual list in the data does only seem to include 120 concepts

There is also a lot of confusion in the raw/ folder, including four different concept-files. How do we best proceed with this?

**Comment by LinguList** [comment]
In fact, the data is fine now, and we can close this issue. The confusion was a bit that I had forgotten that the problems had already been fixed, or that we did not close the issue. I recently check the data, and my update from last week should make everything clear. The raw folder is a mess, but the CLDF data is not.

**Comment by LinguList** [comment]
As far as I am aware, no Zhang-2019-122 is in the concepticon, the list is only in etc in this repo, and should be removed from there.

**Comment by LinguList** [comment]
So this datasets can be considered to have been fixed and brought up to Concepticon 3.0.
