### ISSUE TITLE
Adding list to Concepticon

### ISSUE THREAD

**Issue by mathildavz** [lexibank/zhangrgyalrong#8]
I'm currently working on adding this list to Concepticon. There are several files under https://github.com/lexibank/zhangrgyalrong/tree/master/raw that contain mappings, which are all, however, not finished yet. @LinguList, which file should I use?

**Comment by LinguList** [comment]
Sorry, somehow, we did not check that this WAS already mapped! WE need to be a bit more careful with the lists we asked you to do, this is the second time. We'll check more thoroughly, or please write to us in the CALC chat when you start with a particular concept list?
